/**
 * Assemble the Design Pack folder tree and zip it (Design Pack spec §2).
 *
 * The route handler (app/api/export/route.ts) loads data, derives tokens, and
 * generates brief.md / deliverables via Gemini, then hands everything here. This
 * module is pure: given the parts, it builds the deterministic folder + zip.
 *
 * Deterministic fallbacks (readme, brief, deliverables) live here too, so a pack
 * is still valid when the LLM is unavailable.
 */
import JSZip from "jszip";
import type { BrandDataObject } from "../brand-data";
import type { DesignTokens } from "../tokens";

export interface ReferenceManifestItem {
  file?: string;
  type: string;
  source?: string;
  sentiment?: "love" | "like" | "avoid";
  note?: string;
  extracted?: { palette: string[]; fonts: string[] };
}

export interface AssetFile {
  path: string; // relative path inside the pack, e.g. "references/inspiration-01.jpg"
  data: Uint8Array;
}

export interface DesignPackInput {
  projectId: string;
  brandData: BrandDataObject;
  tokens: DesignTokens;
  brief: string;
  deliverables: { name: string; content: string }[];
  references: ReferenceManifestItem[];
  assetFiles: AssetFile[];
  date: string; // ISO date (YYYY-MM-DD), passed in (no Date.now in shared code)
}

/* ----------------------------- README ----------------------------- */

export function buildReadme(bd: BrandDataObject, projectId: string, date: string): string {
  const client = bd.project.client || "Client";
  return `# ${client} — Design Pack
Generated by Discovery Studio · ${date} · project ${projectId}

## What's inside
- brief.md — the design direction in plain language
- brand-data.json — structured source of truth (colors, type, logo, audience…)
- tokens/brand.tokens.json — design tokens (DTCG). DESIGN AGAINST THESE.
- references/ — inspiration + competitors, tagged love/like/avoid
- assets/ — client's existing logo/guidelines (if any)
- deliverables/ — one brief per thing to design

## Instructions for Claude Design
1. Read brief.md for direction, then brand-data.json for exact values.
2. Use tokens/brand.tokens.json as the source of truth for color, type, spacing — do not invent new values; extend the scale if needed and note it.
3. Study references/ — match the "love" set, avoid the "avoid" set.
4. Design each item in deliverables/ in its listed order.
5. Flag any missing input instead of guessing; keep everything on-token.
`;
}

/* ----------------------------- fallback brief ----------------------------- */

export function fallbackBrief(bd: BrandDataObject): string {
  const list = (arr: string[]) => (arr.length ? arr.join(", ") : "—");
  const offerings = bd.business.offerings.map((o) => o.name);
  const segments = bd.audience.segments.map((s) => s.name);
  const personality = bd.brand.personality.map((p) => p.trait);
  return `# ${bd.project.client || "Client"} — Design Brief

## Snapshot
${bd.business.description || "—"}
Type: ${bd.business.type || "—"}. Sells: ${list(offerings)}.
What makes them different: ${bd.business.differentiator || "—"}.
${bd.business.story ? `Story: ${bd.business.story}` : ""}

## Purpose
Mission: ${bd.brand?.mission || "—"}. Vision: ${bd.brand?.vision || "—"}.
Values: ${list(bd.brand?.values ?? [])}.

## Audience
For: ${list(segments)} (${bd.audience.b2x || "—"}). ${bd.audience.demographics ? `Demographics: ${bd.audience.demographics}.` : ""}
Jobs to be done: ${list(bd.audience.jobsToBeDone)}. ${bd.audience.painPoints ? `Pain points: ${bd.audience.painPoints}.` : ""}

## Market
Competitors: ${list(bd.market.competitors.map((c) => c.name))}. Positioning: ${list(bd.market.positioning.map((p) => p.value))}.

## Brand personality & archetype
Archetype: ${bd.brand.archetype || "—"}. Personality: ${list(personality)}.
Keywords: ${list(bd.brand.keywords)}.

## Voice & tone
Person: ${bd.voice.person || "—"}. Emoji: ${bd.voice.emoji ? "yes" : "no"}.
${bd.voice.examples.length ? `Examples:\n- ${bd.voice.examples.join("\n- ")}` : ""}

## Visual direction
Style cluster: ${bd.visualStyle.cluster || "—"}. Mood: ${list(bd.visualStyle.moodWords)}.
Imagery: ${list(bd.imagery.mode)}${bd.imagery.iconStyle ? `, ${bd.imagery.iconStyle} icons` : ""}.

## Logo direction
Preferred types: ${list(bd.logo.preferredTypes)}. Avoid: ${list(bd.logo.avoid)}.
${bd.logo.notes || ""}

## Color direction
${bd.color.paletteName ? `Brand palette: **${bd.color.paletteName}** — ${list((bd.color.chosenPalette ?? []).map((c) => c.hex))}.\n` : ""}Direction: ${bd.color.direction || "—"}. Locked: ${list(bd.color.locked.map((c) => c.hex))}.
Light/dark: ${bd.color.lightDark || "—"}. (Exact values live in tokens/brand.tokens.json.)

## Surfaces to design
${bd.surfaces.length ? bd.surfaces.map((s) => `- ${s.kind}`).join("\n") : "—"}

## Deliverables to design
${bd.deliverables?.length ? bd.deliverables.map((d) => `- ${d}`).join("\n") : "—"}

## Goals
Primary: ${bd.goals.primary || "—"}. Measured by: ${list(bd.goals.metrics)}.
`;
}

/* ----------------------------- fallback deliverables ----------------------------- */

export function fallbackDeliverables(bd: BrandDataObject): { name: string; content: string }[] {
  const out: { name: string; content: string }[] = [];

  out.push({
    name: "design-system.md",
    content: `# Design System

## Goal
Produce the full token set + a component kit for ${bd.project.client || "the brand"}.

## Use from the pack
- tokens/brand.tokens.json — the source of truth (color, type, spacing, radius, shadow).
- brand-data.json — personality, style cluster, light/dark preference.

## Components to produce
Buttons (primary/secondary/ghost), inputs, select, cards, badges, tabs, modal, nav, footer.
Show each on a preview page in light and dark as applicable.

## Acceptance
Every component uses ONLY token values; no hard-coded colors or sizes.
`,
  });

  out.push({
    name: "brand-guidelines.md",
    content: `# Brand Guidelines

Assemble the 6 standard sections from this pack:
1. Logo usage — preferred types: ${bd.logo.preferredTypes.join(", ") || "—"}.
2. Color — from tokens/brand.tokens.json.
3. Typography — display/body families from tokens.
4. Voice — ${bd.voice.person || "—"}, emoji ${bd.voice.emoji ? "yes" : "no"}.
5. Imagery — ${bd.imagery.mode.join(", ") || "—"}.
6. Do / Don't — derived from the "love" vs "avoid" references.
`,
  });

  out.push({
    name: "logo.md",
    content: `# Logo

## Chosen type(s)
${bd.logo.preferredTypes.join(", ") || "—"}

## Must convey
${bd.logo.notes || "—"}

## Variations needed
Primary, stacked, mark-only, monochrome. Provide color-on-light and color-on-dark.

## Avoid
${bd.logo.avoid.join(", ") || "—"}
`,
  });

  if (bd.surfaces.some((s) => /website|web app|app|site/i.test(s.kind))) {
    const web = bd.surfaces.find((s) => /website|web app|app|site/i.test(s.kind));
    out.push({
      name: "website.md",
      content: `# Website

## Surfaces & screens
- ${web?.kind || "Website"}: ${web?.screens.length ? web.screens.join(", ") : "Home, About, Services, Work, Contact"}
- Components: ${web?.components.length ? web.components.join(", ") : "header, hero, cards, meta grid, footer, CTA band"}

Layout feel: ${bd.visualStyle.cluster || "clean, modern"}; ${bd.color.lightDark || "dark"}-first.
Use content/website-copy.md for real copy when available.
`,
    });
  }

  if (bd.automation?.needs?.length) {
    out.push({
      name: "automation.md",
      content: `# AI Automation

## Goal
Build the AI automation that takes repetitive work off the client's plate.

## Automations to build
${bd.automation.needs.map((n) => `- ${n}`).join("\n")}

## Level
${bd.automation.level || "—"}

## Workflows to smooth (their words)
${bd.automation.workflows.length ? bd.automation.workflows.map((w) => `- ${w}`).join("\n") : "—"}

${bd.automation.notes ? `## Notes\n${bd.automation.notes}` : ""}

## Acceptance
Each automation has a clear trigger, the action it performs, and where a human stays in the loop.
`,
    });
  }

  if (bd.surfaces.some((s) => /social/i.test(s.kind))) {
    out.push({
      name: "social.md",
      content: `# Social Kit

Templated post / story / banner set using the brand tokens and voice.
Voice: ${bd.voice.person || "—"}, emoji ${bd.voice.emoji ? "yes" : "no"}.
`,
    });
  }

  if (bd.surfaces.some((s) => /packaging/i.test(s.kind)) || bd.business.type === "product") {
    out.push({
      name: "packaging.md",
      content: `# Packaging

Product colors: ${(bd.color.productColors ?? []).map((c) => c.hex).join(", ") || "see brand palette"}.
Needs: ${bd.product?.packagingNeeds.join(", ") || "—"}.
`,
    });
  }

  return out;
}

/* ----------------------------- zip assembly ----------------------------- */

export async function buildDesignPack(input: DesignPackInput): Promise<Uint8Array> {
  const { brandData, tokens, brief, deliverables, references, assetFiles, projectId, date } = input;
  const zip = new JSZip();
  const root = zip.folder("design-pack")!;

  root.file("README.md", buildReadme(brandData, projectId, date));
  root.file("brief.md", brief);
  root.file("brand-data.json", JSON.stringify(brandData, null, 2));
  root.folder("tokens")!.file("brand.tokens.json", JSON.stringify(tokens, null, 2));

  const refFolder = root.folder("references")!;
  refFolder.file("references.json", JSON.stringify(references, null, 2));

  const delFolder = root.folder("deliverables")!;
  for (const d of deliverables) delFolder.file(d.name, d.content);

  // Drop reference/asset binaries at their relative paths inside the pack.
  for (const f of assetFiles) root.file(f.path, f.data);

  return zip.generateAsync({ type: "uint8array" });
}
